plugins:
  gofmt:
    enabled: true
  govet:
    enabled: true
  golint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
    - "**.go"
exclude_patterns:
  - vendor/
  - tmp/
  - src/html/templates/bindata.go
