version: "2"
plugins:
  gofmt:
    enabled: true
  govet:
    enabled: true
  golint:
    enabled: true
  fixme:
    enabled: true
exclude_patterns:
  - vendor/
  - tmp/
  - src/html/templates/bindata.go
