language: go
go:
  - 1.9.x
  - tip
install:
  - make deps
  - npm install -g codeclimate-test-reporter
script:
  - make coverage
after_success:
  - codeclimate-test-reporter < ./tmp/coverage.txt
cache:
  directories:
    - $GOPATH/bin
    - $HOME/.npm
    - vendor
  timeout: 1000
notifications:
  email:
    on_success: never
    on_failure: always
